spring:
  application:
    name: spring-phimnets-streaming-service

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  # spring-cloud-aws
  cloud:
    aws:
      region:
        static: ap-southeast-1
      credentials:
        access-key: AWS_ACCESS_KEY
        secret-key: AWS_SECRET_KEY
  # Database configurations
  datasource:
    url: jdbc:mysql://localhost:3306/video
    username: root
    password: my-root-password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
# S3 bucket
s3:
  bucket:
    name: videos-hls


files:
  video:
    src: videos/
    hsl: videos-hls/
    chunk: videos-chunk/